export const ADD_ELEMENT = 'ADD_ELEMENT';
export const EDIT_ELEMENT = 'EDIT_ELEMENT';
export const DESTROY_ELEMENT = 'DESTROY_ELEMENT';
export const MOVE_ELEMENT = 'MOVE_ELEMENT';
export const EDIT_META = 'EDIT_META';

export const PREMAIL_LOADING = 'PREMAIL_LOADING';
export const PREMAIL_SUCCESS = 'PREMAIL_SUCCESS';
export const PREMAIL_FAILURE = 'PREMAIL_FAILURE';
